services:
  - type: web
    name: auction-viewer
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    rootDir: auction-viewer
    envVars:
      - key: NODE_ENV
        value: production
