"""initial schema

Revision ID: 324eee63c280
Revises:
Create Date: 2026-02-15 22:53:43.249682

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '324eee63c280'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_list', schema=None) as batch_op:
        batch_op.alter_column('docid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)

    with op.batch_alter_table('auction_list_cleaned', schema=None) as batch_op:
        batch_op.alter_column('사건번호',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_list_cleaned', schema=None) as batch_op:
        batch_op.alter_column('사건번호',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('auction_list', schema=None) as batch_op:
        batch_op.alter_column('docid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
